### ISSUE TITLE
Change the workflow to update the original diff comment vs adding new comments on PR updates

### ISSUE THREAD

**Issue by SudeepSidhu** [SudeepSidhu/diff-action#3]
Current way adds a bit more noise to the PRs than we want, lets see if we can find a way to update the original comment if there is one, else proceed as usual

**Comment by kasrababaei** [comment]
A suggestion that might work:

```
    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Build output

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Diff stats:
          ```
          ${{ steps.run-git-diff.outputs.diff-output }}
          ```
        edit-mode: replace
```
